# Generated by Django 4.2.6 on 2023-11-29 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_system', '0003_user_logs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='item_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='logs',
            name='user_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='validation',
            field=models.CharField(default='Pending', max_length=50),
        ),
    ]
