# Generated by Django 4.2.6 on 2023-11-29 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_system', '0004_alter_logs_item_id_alter_logs_user_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logs',
            old_name='user_id',
            new_name='username',
        ),
        migrations.AlterField(
            model_name='user',
            name='validation',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved')], default='Pending', max_length=50),
        ),
    ]
